webapp:
  extends:
    file: docker-compose.yml
    service: webapp
  image: quay.io/autodesk_bionano/gctor_webapp${BNR_ENV_TAG}
  environment:
    API_END_POINT: http://internal-lb${BNR_ENV_URL_SUFFIX}.bionano.bio:8080/api
    HOST_URL: https://geneticconstructor${BNR_ENV_URL_SUFFIX}.bionano.autodesk.com
    NODE_ENV: ${NODE_ENV}
    GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    CAPTCHA_SECRET_REGISTER: ${CAPTCHA_SECRET_REGISTER}
    NO_DOCKER: "true"
    STORAGE_API: http://internal-lb${BNR_ENV_URL_SUFFIX}.bionano.bio:4747/api
    AWS_ACCESS_KEY_ID: ${GC_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${GC_AWS_SECRET_ACCESS_KEY}
    BNR_ENVIRONMENT: ${BNR_ENVIRONMENT}
    BNR_ENV_TAG: ${BNR_ENV_TAG}
    BNR_ENV_URL_SUFFIX: ${BNR_ENV_URL_SUFFIX}
    EMAIL: ${EMAIL}
    VERBOSE_REQUEST_LOGS: ${VERBOSE_REQUEST_LOGS}
  command:
    npm run server-auth
  log_driver: json-file
  restart: always
  # 8 GB RAM for gc docker stats as of 22-Mar-17 show max mem usage of 6.5 GB in dev
  mem_limit: 8400000000 
  ports:
    - "3000"
