webapp:
  extends:
    file: docker-compose.yml
    service: webapp
  image: quay.io/autodesk_bionano/gctor_webapp${BNR_ENV_TAG}
  environment:
    API_END_POINT: http://internal-lb.{BNR_ENV_URL_SUFFIX}.bionano.bio:8080/api
    HOST_URL: https://geneticconstructor${BNR_ENV_URL_SUFFIX}.bionano.autodesk.com
    NODE_ENV: ${NODE_ENV}
    GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    NO_DOCKER: "true"
    STORAGE_API: http://internal-lb.{BNR_ENV_URL_SUFFIX}.bionano.bio:4747/api
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    BNR_ENVIRONMENT: ${BNR_ENVIRONMENT}
    BNR_ENV_TAG: ${BNR_ENV_TAG}
    BNR_ENV_URL_SUFFIX: ${BNR_ENV_URL_SUFFIX}
  command:
    npm run server-auth
  log_driver: json-file
  restart: always
